import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  apiSidebar: [
    {
      type: "category",
      label: "@stoatx/client",
      items: [
        {
          type: "autogenerated",
          dirName: "client",
        },
      ],
    },
  ],
};

export default sidebars;
