import { APIRoutes } from "stoat-api";

/**
 * This file was copied from https://github.com/stoatchat/javascript-client-api/blob/main/src/params.ts
 * If any new endpoints are added, they should be added here to ensure the type safety of query parameters.
 */
export const queryParams = {
  "/": { get: [] },
  "/users/@me": { get: [] },
  "/users/{target}": { get: [], patch: [] },
  "/users/{target}/flags": { get: [] },
  "/users/@me/username": { patch: [] },
  "/users/{target}/default_avatar": { get: [] },
  "/users/{target}/profile": { get: [] },
  "/users/dms": { get: [] },
  "/users/{target}/dm": { get: [] },
  "/users/{target}/mutual": { get: [] },
  "/users/{target}/friend": { put: [], delete: [] },
  "/users/{target}/block": { put: [], delete: [] },
  "/users/friend": { post: [] },
  "/bots/create": { post: [] },
  "/bots/{target}/invite": { get: [], post: [] },
  "/bots/{bot_id}": { get: [], delete: [], patch: [] },
  "/bots/@me": { get: [] },
  "/channels/{target}/ack/{message}": { put: [] },
  "/channels/{target}": { get: [], delete: ["leave_silently"], patch: [] },
  "/channels/{target}/members": { get: [] },
  "/channels/{target}/invites": { post: [] },
  "/channels/{target}/messages": { get: ["limit", "before", "after", "sort", "nearby", "include_users"], post: [] },
  "/channels/{target}/search": { post: [] },
  "/channels/{target}/messages/{msg}/pin": { post: [], delete: [] },
  "/channels/{target}/messages/{msg}": { get: [], delete: [], patch: [] },
  "/channels/{target}/messages/bulk": { delete: [] },
  "/channels/create": { post: [] },
  "/channels/{group_id}/recipients/{member_id}": { put: [], delete: [] },
  "/channels/{target}/join_call": { post: [] },
  "/channels/{target}/end_ring/{target_user}": { put: [] },
  "/channels/{target}/permissions/{role_id}": { put: [] },
  "/channels/{target}/permissions/default": { put: [] },
  "/channels/{target}/messages/{msg}/reactions/{emoji}": { put: [], delete: ["user_id", "remove_all"] },
  "/channels/{target}/messages/{msg}/reactions": { delete: [] },
  "/channels/{channel_id}/webhooks": { get: [], post: [] },
  "/servers/create": { post: [] },
  "/servers/{target}": { get: ["include_channels"], delete: ["leave_silently"], patch: [] },
  "/servers/{target}/ack": { put: [] },
  "/servers/{server}/channels": { post: [] },
  "/servers/{target}/members": { get: ["exclude_offline"] },
  "/servers/{server_id}/members/{member_id}": { get: ["roles"], delete: [], patch: [] },
  "/servers/{target}/members_experimental_query": { get: ["query", "experimental_api"] },
  "/servers/{server}/bans/{target}": { put: [], delete: [] },
  "/servers/{target}/bans": { get: [] },
  "/servers/{target}/invites": { get: [] },
  "/servers/{target}/roles": { post: [] },
  "/servers/{target}/roles/{role_id}": { get: [], delete: [], patch: [] },
  "/servers/{target}/permissions/{role_id}": { put: [] },
  "/servers/{target}/permissions/default": { put: [] },
  "/servers/{target}/emojis": { get: [] },
  "/servers/{target}/roles/ranks": { patch: [] },
  "/invites/{target}": { get: [], post: [], delete: [] },
  "/custom/emoji/{emoji_id}": { get: [], put: [], delete: [], patch: [] },
  "/safety/report": { post: [] },
  "/auth/account/create": { post: [] },
  "/auth/account/reverify": { post: [] },
  "/auth/account/delete": { put: [], post: [] },
  "/auth/account/": { get: [] },
  "/auth/account/disable": { post: [] },
  "/auth/account/change/password": { patch: [] },
  "/auth/account/change/email": { patch: [] },
  "/auth/account/verify/{code}": { post: [] },
  "/auth/account/reset_password": { post: [], patch: [] },
  "/auth/session/login": { post: [] },
  "/auth/session/logout": { post: [] },
  "/auth/session/all": { get: [], delete: ["revoke_self"] },
  "/auth/session/{id}": { delete: [], patch: [] },
  "/auth/mfa/ticket": { put: [] },
  "/auth/mfa/": { get: [] },
  "/auth/mfa/recovery": { post: [], patch: [] },
  "/auth/mfa/methods": { get: [] },
  "/auth/mfa/totp": { put: [], post: [], delete: [] },
  "/onboard/hello": { get: [] },
  "/onboard/complete": { post: [] },
  "/policy/acknowledge": { post: [] },
  "/push/subscribe": { post: [] },
  "/push/unsubscribe": { post: [] },
  "/sync/settings/fetch": { post: [] },
  "/sync/settings/set": { post: ["timestamp"] },
  "/sync/unreads": { get: [] },
  "/webhooks/{webhook_id}/{token}/{message_id}": { delete: [], patch: [] },
  "/webhooks/{webhook_id}/{token}": { get: [], post: [], delete: [], patch: [] },
  "/webhooks/{webhook_id}": { get: [], delete: [], patch: [] },
  "/webhooks/{webhook_id}/{token}/github": { post: [] },
};

export type ValidPath<M extends APIRoutes["method"]> = Extract<APIRoutes, { method: M }>["path"];

export type RouteResponse<M extends APIRoutes["method"], P extends string> = Extract<
  APIRoutes,
  { method: M; path: P }
>["response"];

export type RouteParams<M extends APIRoutes["method"], P extends string> = Extract<
  APIRoutes,
  { method: M; path: P }
>["params"];