min_version = { soft = "2026.5.15", hard = "2026.5.12" }

[tools]
node = "26.2.0"
pnpm = "11.5.1"
gh = "2.92.0"
"aqua:git-town/git-town" = "23.0.1"

[tasks.ci]
description = "Task group for CI checks"
run = [
    { task = "install:frozen" },
    { task = "build" },
    { tasks = ["build:check", "format"] }
]
